# Generated by Django 4.0.4 on 2022-06-30 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0004_alter_comentario_autor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='autor',
            new_name='post',
        ),
    ]
