# Generated by Django 4.0.4 on 2022-06-30 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0005_rename_autor_comentario_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='post',
            new_name='autor',
        ),
    ]
