# Generated by Django 4.0.4 on 2022-06-30 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0007_rename_autor_comentario_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=models.ImageField(blank=True, default='avatar/loginDefault.jpg', null=True, upload_to='avatares'),
        ),
    ]
