# Generated by Django 4.0.4 on 2022-07-01 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0009_alter_avatar_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('fecha', '-id')},
        ),
        migrations.AlterField(
            model_name='post',
            name='fecha',
            field=models.DateField(),
        ),
    ]
