# Generated by Django 4.0.4 on 2022-07-01 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0012_alter_post_options_comentario_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='usuario',
        ),
    ]
