# Generated by Django 4.0.4 on 2022-07-04 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0019_alter_avatar_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=models.ImageField(blank=True, default='static\\AppBlog\x07ssets\\img\\loginDefault.jpg', null=True, upload_to='avatares'),
        ),
    ]
