# Generated by Django 4.0.4 on 2022-07-05 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0023_alter_avatar_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
