# Generated by Django 4.0.4 on 2022-07-05 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0024_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-fecha',)},
        ),
    ]
